### ISSUE TITLE
HighlightDuplicatesCommand bug

### ISSUE THREAD

**Issue by Argimko** [LordBrom/HighlightDuplicates#10]
Hello LordBrom,

Thank you for you package!

Seems `HighlightDuplicatesCommand()` do not toggle highlighting for the active view (as I expect :)

Thank you!

**Comment by LordBrom** [comment]
Hey Argimko, 

would you be able to add more detail to the issue you are having?

**Comment by LordBrom** [comment]
If you experience this again, please reopen and give details. Thanks,
