### ISSUE TITLE
ToggleSelectDuplicatesCommand improvement

### ISSUE THREAD

**Issue by Argimko** [LordBrom/HighlightDuplicates#11]
Also, it is possible to enable soft undo/redo with Ctrl+U at ToggleSelectDuplicatesCommand()

You just can add `self.view.end_edit(edit)`:
```
class ToggleSelectDuplicatesCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        select_duplicates(self.view)

        # this is a hack to enable soft_undo, more details:
        # https://github.com/aronwoost/sublime-expand-region/blob/master/ExpandRegion.py
        self.view.end_edit(edit)
```

**Comment by LordBrom** [comment]
Ah, I see. Thank you for this input.

I think I've got this working locally, I want to play around with it a bit more, but I'll push the update before to long.

**Comment by LordBrom** [comment]
This has been updated in the plugin. v1.5.0
