### ISSUE TITLE
Have a setting for the line scope or word whitelist

### ISSUE THREAD

**Issue by stephen147** [LordBrom/HighlightDuplicates#13]
This is a really great plugin.

An option for the min number of lines that it looks for.

Or probably even better a whitelist of words to ignore.

As you can see here that would be very useful:
![image](https://user-images.githubusercontent.com/14054664/114321269-d8dc5600-9b11-11eb-9394-c500102ae542.png)

**Comment by LordBrom** [comment]
Thanks for using it, I'm glad you are finding it helpful. Sorry, this took so long to get around to.

I am not entirely sure how your "min number of lines" request would work, but I was able to figure out the white list easily enough. I'm going to do a bit more testing on it, and then I'll have it out either today or tomorrow. (#14)

When I deploy this update I am going to close this issue out, but if you want to open another one with a bit more details on the "min number of lines" request, I'll be happy to take a look.

**Comment by stephen147** [comment]
Yes, the min number would work like that. It would be useful as the words wouldn't have to be added to the whitelist manually as more often than not there would be no more than 2 duplicate lines.
