### ISSUE TITLE
Short "words" dont get detected as duplicates

### ISSUE THREAD

**Issue by angrybb** [LordBrom/HighlightDuplicates#6]
3 chars or less don't get detected
![sublimehl](https://user-images.githubusercontent.com/10758654/74344446-e468ab80-4dac-11ea-8d8f-f24ce789e74e.JPG)

**Comment by LordBrom** [comment]
Hey, sorry I didn't see this earlier. I think originally there was performance concerns, with checking every single line. The plugin was originally for ST2. I will add a setting which will allow you to set the min length of a line to get detected. As to not change current functionality, I will default the setting to 4.

**Comment by LordBrom** [comment]
Released version 1.4.0, which includes a setting where you can change which lines get ignored. Hopefully that gives you what you need. Thanks for using the plugin!
